### ISSUE TITLE
compatible for ios plaform 

### ISSUE THREAD

**Issue by almog-kiki** [CreativeInquiry/ofxASM#1]
this project work fine at mac osx with xcode .
but when I try to run on iPhone it's not working well.
when this line:
model.buildModel("muct76.def", "camA_Q.list"); is run,
it  go to alignShape function and I getting "EXC_BAD_ACCESS" when it try to clone  for some matrix, like: 
  newMean = imageSet[0].shapeVec.clone();
what can i do ? its about the models doesn't fit to ios platform ? what is the alternative way ?

**Comment by danomatika** [comment]
What's the program console output? I bet you're not loading the model files from the right paths. There should be something like  "[error] ofxASM: cannot load shape definition ...".

If you're using the example, the correct paths would be:

```
model.buildModel("training/muct76.def", "training/camA_Q.list")
```

Looking at that function, it assumes the module is loaded and tries to open the first image set. If nothing is loaded, you'd get that error since there's nothing at that memory location.

Other than that, I don't know. I haven't tried it on iOS.

**Comment by almog-kiki** [comment]
Hi 
I loaded from the right path . 
I used the example , and its was like u write : "cannot load shape .....", so i changed the location and its was good. 
this is what the console show : 
<code> Loading shape info from /var/mobile/Applications/8D8687AB-96D5-489E-B7FF-A3E9F85A1722/iosStoryboardExample.app/muct76.def
Reading data from /var/mobile/Applications/8D8687AB-96D5-489E-B7FF-A3E9F85A1722/iosStoryboardExample.app/camA_Q.list... </code>
and it is stuck at "void ShapeModel::alignShapes()"
and imageset is not empty.
the problem is the clone() is make the app to crash.

**Comment by danomatika** [comment]
I don't know. clone() is an opencv Matrix function. I set up this addon for someone else and I haven't really used it, so I'm not going to be much help.

**Comment by almog-kiki** [comment]
THE PROBLEM IT WAS THE FRAMEWORKS opencv2.frameworks is in the xcode project

**Comment by danomatika** [comment]
So it's working? Can we close this issue?

**Comment by almog-kiki** [comment]
yes.
thank u for your help .
